name: Release

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      
      - name: Run Tests
        run: go test -v ./...

  build-linux-windows:
    name: Build Linux and Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Build Linux AMD64
        run: GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o ts-edu-linux-amd64 ./cmd

      - name: Build Linux ARM64
        run: GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o ts-edu-linux-arm64 ./cmd

      - name: Build Windows AMD64
        run: GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o ts-edu-windows-amd64.exe ./cmd

      - name: Upload Linux and Windows binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries-linux-windows
          path: |
            ts-edu-linux-amd64
            ts-edu-linux-arm64
            ts-edu-windows-amd64.exe

  build-macos:
    name: Build MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Build MacOS Arm
        run: GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o ts-edu-darwin-arm64 ./cmd

      - name: Codesign MacOS Arm binary
        run: codesign -s - --deep -f ts-edu-darwin-arm64

      - name: Build MacOS AMD64
        run: GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o ts-edu-darwin-amd64 ./cmd

      - name: Codesign MacOS AMD64 binary
        run: codesign -s - --deep -f ts-edu-darwin-amd64

      - name: Upload MacOS binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries-macos
          path: |
            ts-edu-darwin-arm64
            ts-edu-darwin-amd64

  deploy-release:
    name: Deploy Release
    runs-on: ubuntu-latest
    needs: [run-tests, build-linux-windows, build-macos]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Linux and Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries-linux-windows
          path: .

      - name: Download MacOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries-macos
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ts-edu-linux-amd64
            install-linux-amd64.sh
            ts-edu-linux-arm64
            install-linux-arm64.sh
            ts-edu-windows-amd64.exe
            install-windows-amd64.ps1
            ts-edu-darwin-amd64
            install-darwin-amd64.sh
            ts-edu-darwin-arm64
            install-darwin-arm64.sh
